import { useAuth, useUser } from "@clerk/nextjs";
import Head from "next/head";
import Link from "next/link";

export default function Home() {
	const { isSignedIn } = useUser();
	const { signOut } = useAuth();

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main
				className={`flex flex-col gap-y-8 w-full h-full items-center justify-center ${
					isSignedIn ? "bg-green-300" : "bg-red-300"
				}`}
			>
				<h1 className="text-6xl font-bold">Home Page</h1>
				<div className="flex gap-x-8">
					{!isSignedIn ? (
						<>
							<Link
								href="/sign-in"
								className="text-2xl font-bold"
							>
								Sign In
							</Link>
							<Link
								href="/sign-up"
								className="text-2xl font-bold"
							>
								Sign Up
							</Link>
						</>
					) : (
						<>
							<div
								onClick={() => signOut()}
								className="text-2xl font-bold"
							>
								Sign Out
							</div>
						</>
					)}
				</div>
			</main>
		</>
	);
}
